remote_theme: chesterhow/tale

# Site settings
title:          Kier's Blog
description:    "安全/管理学习记录"
# baseurl:        "/tale"
url:            "https://yurenzhang.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Kier
  url:          https://yurenzhang.github.io
  email:        yuren.zhang@outlook.com

# Build settings
markdown:       kramdown
include:
  - _pages
  - _posts

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

  
# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks


permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale